### ISSUE TITLE
StreamData fails to start properly when a single app's tests are ran in an umbrella project

### ISSUE THREAD

**Issue by parkerjm** [whatyouhide/stream_data#111]
tl;dr: once StreamData is added to an umbrella project, it becomes impossible to run the tests for an app individually.

Steps to reproduce:
1. create an umbrella project
2. create an app inside the umbrella with SD configured to start before ExUnit
3. `cd apps/my_app`
4. `mix test`

Expected outcome: SD starts and the tests run

Actual outcome:
```
** (MatchError) no match of right hand side value: {:error, {:stream_data, {'no such file or directory', 'stream_data.app'}}}
    test/test_helper.exs:1: (file)
    (elixir) lib/code.ex:677: Code.require_file/2
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
    (mix) lib/mix/tasks/test.ex:256: Mix.Tasks.Test.run/1
```

**Comment by parkerjm** [comment]
This only occurs when StreamData is added to the umbrella's deps but not to the app's dep list. StreamData is used across several apps in my umbrella, so I put it in the top level mix.exs file, but seems it needs to be added to each app separately since it's getting manually started when tests run.
