### ISSUE TITLE
Bind documentation incorrect

### ISSUE THREAD

**Issue by frekw** [whatyouhide/stream_data#44]
Hi!

I'm trying to get the following example to work (from https://hexdocs.pm/stream_data/StreamData.html#bind/2)

```elixir
StreamData.bind(StreamData.list_of(StreamData.integer()), fn list ->
  StreamData.bind(StreamData.member_of(list), fn elem ->
    StreamData.constant({list, elem})
  end)
end)
```

However, it fails with: 

```
     ** (RuntimeError) cannot generate elements from an empty enumerable
     stacktrace:
       (stream_data) lib/stream_data.ex:663: StreamData.member_of/1
       (stream_data) lib/stream_data.ex:350: anonymous fn/2 in StreamData.bind/2
       (stream_data) lib/stream_data/lazy_tree.ex:60: StreamData.LazyTree.map/2
       (stream_data) lib/stream_data/lazy_tree.ex:87: StreamData.LazyTree.filter_map/2
       (stream_data) lib/stream_data.ex:307: StreamData.bind_filter/5
       (stream_data) lib/stream_data.ex:290: anonymous fn/5 in StreamData.bind_filter/3
       (stream_data) lib/stream_data.ex:160: StreamData.call/3
       (stream_data) lib/stream_data.ex:305: StreamData.bind_filter/5
       (stream_data) lib/stream_data.ex:290: anonymous fn/5 in StreamData.bind_filter/3
       (stream_data) lib/stream_data.ex:160: StreamData.call/3
       (stream_data) lib/stream_data/lazy_tree.ex:60: StreamData.LazyTree.map/2
       (stream_data) lib/stream_data.ex:311: StreamData.bind_filter/5
       (stream_data) lib/stream_data.ex:290: anonymous fn/5 in StreamData.bind_filter/3
       (stream_data) lib/stream_data.ex:160: StreamData.call/3
       (stream_data) lib/stream_data/lazy_tree.ex:60: StreamData.LazyTree.map/2
       (stream_data) lib/stream_data.ex:311: StreamData.bind_filter/5
       (stream_data) lib/stream_data.ex:290: anonymous fn/5 in StreamData.bind_filter/3
       (stream_data) lib/stream_data.ex:160: StreamData.call/3
       (stream_data) lib/stream_data/lazy_tree.ex:60: StreamData.LazyTree.map/2
```

which, as far as I can tell, was changed in https://github.com/whatyouhide/stream_data/commit/af4e64f1d8ef75cc7fc067faa1aaa38aad1a1112

Should this example be possible? I'm running into a similar issue when trying build generators based on output from `list_of`.

**Comment by josevalim** [comment]
I wonder if it is better to simply emit nothing for an empty list in such
generators otherwise we will force users to check for not empty themselves.
Thoughts @whatyouhide?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whatyouhide** [comment]
@josevalim what do you mean by "emit nothing"? Our generators always emit terms 😕

**Comment by josevalim** [comment]
Basically we would tell the parent generator to move to the next element?

**Comment by whatyouhide** [comment]
@josevalim this is not something we support and we would have to change the semantics of the whole stream_data in order to do it. We would have to introduce a return value of `{:ok, lazy_tree} | :error` instead of `lazy_tree` from generators basically.

**Comment by josevalim** [comment]
@whatyouhide I see. do we assume that lazy tree is always infinite? Can't a part of the tree run out of values?

**Comment by whatyouhide** [comment]
@josevalim it's not infinite, but we only traverse the tree when shrinking. When generating we always use either the whole tree as a unit or the root (which is the actual generated value).

**Comment by josevalim** [comment]
@whatyouhide ok, so I am out of ideas. :D Any suggestion on how to address this issue then?

**Comment by whatyouhide** [comment]
@josevalim well yeah I really think the solution is to use `StreamData.list_of(integer(), min_length: 1)`. Semantically, I don't want you to allow to define an incorrect test (the property that a member of a list is `in` the list is not true because it doesn't hold for empty lists).

**Comment by frekw** [comment]
Could another potential solution be to instead do

```elixir
map(list_of(integer()), fn list ->
  bind(member_of(list), fn elem ->
    constant({list, elem})
  end)
end)
```

and update the docs accordingly?

I'm still very much trying to wrap my head around composition of generators, but to me that approach would seem intuitive.

**Comment by whatyouhide** [comment]
@frekw the problem is not the use of `bind` vs `map` or similar thing.

Your approach suffers from the same problem described in the original example. On a semantic level, you cannot take a member of an empty list (because an empty list has no members), so a property that wishes to take an empty member out of a list needs to ensure the list is never empty. After all `elem in list` is always `false` if `list == []`, so the property is broken whatever `elem` you could take out of the list, hence the property must be correctly specified with `list_of(..., min_length: 1)`.

See what I mean?

**Comment by frekw** [comment]
Gotcha! As I said, I'm still trying to understand how all the pieces are supposed to fit together.

When generating tests, however, it would be pretty convenient to not have to separate the two cases as much, but perhaps that could be remedied by something similar to

```
tuples = nullable(map(list_of(integer()), fn list ->
  bind(member_of(list), fn elem ->
    constant({list, elem})
  end)
end))

# ...

gen all tuple <- tuples(), do: # tuple is either {list, elem} or nil.
```

**Comment by whatyouhide** [comment]
@frekw I still don't see a use case for this though. If we're talking about the original example (generating tuples of a list and an element of that list), it still doesn't make sense to generate a tuple where the list is `[]` because then what can the element be? So I still believe that semantically we should go with `min_length: 1`. What do you mean by

> not have to separate the two cases as much

also? If you generate `{list, elem} | nil`, what do you use `nil` for?

Btw it's easy to do what you did in the example today with basically the same amount of code:

```elixir
map(list_of(integer()), fn
  [] ->
    constant(nil)
  list ->
    bind(member_of(list), &constant({list, &1})
end)
```

**Comment by keathley** [comment]
We've had to do something similar in some of our generators but we used `nonempty/1` which seemed to convey the most meaning to us.
