### ISSUE TITLE
Investigate proper stacktraces for filters in check all / gen all

### ISSUE THREAD

**Issue by josevalim** [whatyouhide/stream_data#46]

**Comment by whatyouhide** [comment]
```
**  1) test gen all (ExUnitPropertiesTest)
     test/ex_unit_properties_test.exs:6
     ** (StreamData.FilterTooNarrowError) too many (10) consecutive elements were filtered out. Make sure to avoid filters that are too strict and filter out too many elements and make sure a small generation size doesn't affect the filter too heavily (such as when empty lists are filtered out but small generation size forces generation of many empty lists)
     code: check all {string, list} <- data do
     stacktrace:
       (stream_data) lib/stream_data.ex:301: anonymous fn/5 in StreamData.bind_filter/3
       (stream_data) lib/stream_data.ex:160: StreamData.call/3
       (stream_data) lib/stream_data/lazy_tree.ex:60: StreamData.LazyTree.map/2
       (stream_data) lib/stream_data.ex:318: StreamData.bind_filter/5
       (stream_data) lib/stream_data.ex:296: anonymous fn/5 in StreamData.bind_filter/3
       (stream_data) lib/stream_data.ex:160: StreamData.call/3
       (stream_data) lib/stream_data.ex:312: StreamData.bind_filter/5
       (stream_data) lib/stream_data.ex:296: anonymous fn/5 in StreamData.bind_filter/3
       (stream_data) lib/stream_data.ex:160: StreamData.call/3
       (stream_data) lib/stream_data.ex:1788: StreamData.check_all/6
       test/ex_unit_properties_test.exs:15: (test)
```
