### ISSUE TITLE
list_of(float(), min_length: 2) causes FunctionClauseError

### ISSUE THREAD

**Issue by rbino** [whatyouhide/stream_data#90]
Hi,
I've found a strange behavior while experimenting with stream_data.
I've tried to isolate the minimal example to reproduce it.

If this module is executed with `mix test test/property_test`
```elixir
defmodule PropertyTest do
  use ExUnit.Case
  use ExUnitProperties

  property "this fails fine" do
    check all sample_list <- list_of(integer(), min_length: 2) do
      assert length(sample_list) > 2
    end
  end

  property "this does not" do
    check all sample_list <- list_of(float(), min_length: 2) do
      assert length(sample_list) > 2
    end
  end
end
```

the first testcase will "fail correctly" printing
```
  1) property this fails fine (PropertyTest)
     test/property_test.exs:5
     Failed with generated values (after 0 successful run(s)):
     
         sample_list <- list_of(integer(), min_length: 2)
         #=> [0, 0]
     
     Assertion with > failed, both sides are exactly equal
     code: assert length(sample_list) > 2
     left: 2
     stacktrace:
       test/property_test.exs:7: anonymous fn/2 in PropertyTest."property this fails fine"/1
       (stream_data) lib/stream_data.ex:2053: StreamData.shrink_failure/6
       (stream_data) lib/stream_data.ex:2017: StreamData.check_all/7
       test/property_test.exs:6: (test)
```

while the second one will "fail failing" printing
```
  2) property this does not (PropertyTest)
     test/property_test.exs:11
     ** (FunctionClauseError) no function clause matching in StreamData.LazyTree.filter_map/2
     The following arguments were given to StreamData.LazyTree.filter_map/2:
     
         # 1
         false
     
         # 2
         #Function<15.28190564/1 in StreamData.bind_filter/5>
     
     Attempted function clauses (showing 1 out of 1):
     
         def filter_map(%StreamData.LazyTree{root: root, children: children}, fun) when is_function(fun, 1)
     
     code: check all sample_list <- list_of(float(), min_length: 2) do
     stacktrace:
       (stream_data) lib/stream_data/lazy_tree.ex:61: StreamData.LazyTree.filter_map/2
       (stream_data) lib/stream_data/lazy_tree.ex:66: anonymous fn/2 in StreamData.LazyTree.filter_map/2
       (elixir) lib/stream.ex:413: anonymous fn/3 in Stream.flat_map/2
       (elixir) lib/stream.ex:825: Stream.do_transform_user/9
       (elixir) lib/stream.ex:1433: Enumerable.Stream.do_each/4
       (elixir) lib/stream.ex:870: Stream.do_enum_transform/10
       (elixir) lib/enum.ex:1847: Enum.map/2
       (elixir) lib/stream.ex:413: anonymous fn/3 in Stream.flat_map/2
       (elixir) lib/stream.ex:825: Stream.do_transform_user/9
       (elixir) lib/stream.ex:1433: Enumerable.Stream.do_each/4
       (elixir) lib/stream.ex:870: Stream.do_enum_transform/10
       (elixir) lib/stream.ex:806: Stream.do_transform/8
       (elixir) lib/stream.ex:1433: Enumerable.Stream.do_each/4
       (elixir) lib/stream.ex:870: Stream.do_enum_transform/10
       (stream_data) lib/stream_data.ex:2045: StreamData.shrink_failure/6
       (stream_data) lib/stream_data.ex:2017: StreamData.check_all/7
       test/property_test.exs:12: (test)
```

**Comment by whatyouhide** [comment]
Thanks for the report @rbino! 💟
